baseURL = "https://calgarygo.org/"
languageCode = "en-us"
title = "Calgary Go"
theme = "calgarygo"

[params]
  github = "https://github.com/calgarygo"
  twitter = "https://twitter.com/calgarygo"
  featured_image = "/images/skyline-calgary-559370.jpg"
  custom_css = ["css/custom.css"]

[menu]
  [[menu.main]]
    identifier = "coc"
    name = "Code of Conduct"
    url = "https://github.com/calgarygo/CodeOfConduct"

